# Generated by Django 3.2.6 on 2021-10-31 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('facility', models.CharField(max_length=10000)),
                ('avg_price', models.CharField(max_length=7)),
                ('n_time_occupied', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('occupied', 'occupied'), ('free', 'free')], default='free', max_length=10)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('role', models.CharField(choices=[('user', 'user'), ('landlord', 'landlord')], default='user', max_length=10)),
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='room_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_photos/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_payed', models.CharField(max_length=7)),
                ('staytime', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('occupied', 'occupied'), ('free', 'free')], default='occupied', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
    ]
