# Generated by Django 3.2.6 on 2021-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='staytime',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_time_occupied',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
