# Generated by Django 3.2.6 on 2021-11-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211031_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rate',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
