# Generated by Django 3.2.6 on 2021-11-26 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document',
            field=models.FileField(blank='true', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='document_type',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupied_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
