# Generated by Django 3.2.6 on 2022-01-15 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqueries',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
