# Generated by Django 3.2.6 on 2022-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userqueries_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='inqiery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10)),
                ('isverified', models.CharField(choices=[('0', '0'), ('1', '1')], default=0, max_length=2)),
                ('status', models.CharField(choices=[('subscribed', 'subscribed'), ('unsubscribed', 'unsubscribed')], default='subscribed', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
