# Generated by Django 3.2.6 on 2022-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_inqiery'),
    ]

    operations = [
        migrations.AddField(
            model_name='inqiery',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inqiery',
            name='otp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inqiery',
            name='status',
            field=models.CharField(choices=[('subscribed', 'subscribed'), ('unsubscribed', 'unsubscribed')], default='unsubscribed', max_length=15),
        ),
    ]
