# Generated by Django 3.2.6 on 2022-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220116_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inqiery',
            name='token',
        ),
        migrations.AddField(
            model_name='inqiery',
            name='issocial',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='inqiery',
            name='jwttoken',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='inqiery',
            name='socialtoken',
            field=models.CharField(default='', max_length=500),
        ),
    ]
