# Generated by Django 3.2.6 on 2022-03-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220116_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='advancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=10)),
                ('expire_task_id', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.customer')),
                ('inqiery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.inqiery')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.room')),
            ],
        ),
    ]
