# Generated by Django 3.2 on 2022-03-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customerqueries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerqueries',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inqiery'),
        ),
    ]
