# Generated by Django 3.2 on 2022-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220330_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='is_expire',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0')], default='0', max_length=10),
        ),
    ]
