# Generated by Django 3.2 on 2022-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_advancepayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='is_expire',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('refunded', 'refunded')], default='fail', max_length=10),
        ),
    ]
