# Generated by Django 3.2 on 2022-03-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220331_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
