# Generated by Django 3.2 on 2022-04-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_advancepayment_refund_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
                ('bank_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user_detail')),
            ],
        ),
    ]
