# Generated by Django 3.2.6 on 2022-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_bank_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_detail',
            name='onboarding_completed',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='bank_detail',
            name='account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
