# Generated by Django 3.2 on 2022-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bank_detail_account_id_deauthorised'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='refund_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
